[package]
name = "vulcan"
version = "0.1.0"
authors = ["Safin Singh <safin.singh@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = { version = "1", features = ["spin_no_std"] }
register = { version = "1", features = ["no_std_unit_tests"] }
spin = "0.9"
